name : firstWorkflow
on: push

jobs:
    firstJobName:
        runs-on: ubuntu-latest
        steps:
            - name: Check our repo code
              uses: actions/checkout@v3
            - run: echo "$(cat hello_world.txt)"
